package sistemamusica;

import java.sql.*;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author a18davidlp
 */
public class Pantallaregistro extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pantallaregistro
     */
    Connection co;

    public Pantallaregistro() {
        initComponents();

        try {
            Class.forName("com.mysql.jdbc.Driver.class");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantallaregistro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Grupo1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Titulo = new javax.swing.JTextField();
        Genero = new javax.swing.JTextField();
        Grupo = new javax.swing.JTextField();
        rbFavoritos = new javax.swing.JRadioButton();
        rbNoFavoritos = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        ID = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setText("Registrar canciones");

        Titulo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Titulo.setText("Título de la canción");
        Titulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TituloFocusGained(evt);
            }
        });
        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });

        Genero.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Genero.setText("Género de la canción");
        Genero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GeneroFocusGained(evt);
            }
        });

        Grupo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        Grupo.setText("Grupo compositor");
        Grupo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                GrupoFocusGained(evt);
            }
        });

        Grupo1.add(rbFavoritos);
        rbFavoritos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rbFavoritos.setText("Favoritos");
        rbFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFavoritosActionPerformed(evt);
            }
        });

        Grupo1.add(rbNoFavoritos);
        rbNoFavoritos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        rbNoFavoritos.setText("No favoritos");
        rbNoFavoritos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNoFavoritosActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        ID.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        ID.setText("ID");
        ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                IDFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbFavoritos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbNoFavoritos))
                                .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(jButton1)))
                .addGap(47, 172, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbFavoritos)
                    .addComponent(rbNoFavoritos))
                .addGap(77, 77, 77)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String favorito = "";
        if (rbFavoritos.isSelected()) {
            favorito = "S";
        }
        if (rbNoFavoritos.isSelected()) {
            favorito = "N";
        }

        try {
            co = DriverManager.getConnection("jdbc:mysql://localhost/bd_musica", "root", "");
            Statement stm = co.createStatement();
            stm.executeUpdate("INSERT INTO canciones(id_cancion, Titulo, Genero, Grupo, Favorito) VALUES('" + ID.getText() + "', '" + Titulo.getText() + "', '" + Genero.getText() + "', '" + Grupo.getText() + "', '" + favorito + "')");
        } catch (SQLException ex) {
            Logger.getLogger(Pantallaregistro.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se puede conectar a la base de datos");
        }

        JOptionPane.showMessageDialog(null, "Se ha registrado correctamente");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloActionPerformed

    private void rbFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFavoritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFavoritosActionPerformed

    private void rbNoFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoFavoritosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNoFavoritosActionPerformed

    private void TituloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TituloFocusGained
        // TODO add your handling code here:
        Titulo.setText("");
    }//GEN-LAST:event_TituloFocusGained

    private void GeneroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GeneroFocusGained
        // TODO add your handling code here:
        Genero.setText("");
    }//GEN-LAST:event_GeneroFocusGained

    private void GrupoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_GrupoFocusGained
        // TODO add your handling code here:
        Grupo.setText("");
    }//GEN-LAST:event_GrupoFocusGained

    private void IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_IDFocusGained
        // TODO add your handling code here:
        ID.setText("");
    }//GEN-LAST:event_IDFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Genero;
    private javax.swing.JTextField Grupo;
    private javax.swing.ButtonGroup Grupo1;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Titulo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbFavoritos;
    private javax.swing.JRadioButton rbNoFavoritos;
    // End of variables declaration//GEN-END:variables
}
