package sistemamusica;

import java.sql.*;
import java.util.logging.*;
import javax.swing.JOptionPane;

/**
 *
 * @author a18davidlp
 */
public class Pantallaeliminar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Pantallaeliminar
     */
    public Pantallaeliminar() {
        initComponents();
        try {
            Class.forName("com.mysql.jdbc.Driver.class");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Pantallaregistro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbEliminar = new javax.swing.JLabel();
        tfTitulo2 = new javax.swing.JLabel();
        tfGrupo2 = new javax.swing.JLabel();
        tfTitulo3 = new javax.swing.JTextField();
        tfGrupo3 = new javax.swing.JTextField();
        btEliminar = new javax.swing.JButton();

        lbEliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lbEliminar.setText("Eliminar");

        tfTitulo2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tfTitulo2.setText("Titulo de la canción");

        tfGrupo2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tfGrupo2.setText("Grupo de la canción");

        tfTitulo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTitulo3ActionPerformed(evt);
            }
        });

        tfGrupo3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N

        btEliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btEliminar.setText("ELiminar");
        btEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(tfTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfGrupo3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(tfGrupo2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btEliminar)
                        .addGap(224, 224, 224))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfGrupo2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfTitulo3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGrupo3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(btEliminar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTitulo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTitulo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTitulo3ActionPerformed

    private void btEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarActionPerformed
        try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost/bd_musica", "root", "");
            Statement smt = con.createStatement();
            smt.executeUpdate("DELETE FROM canciones WHERE Titulo LIKE '" + tfTitulo3.getText() + "' OR Grupo LIKE '" + tfGrupo3.getText() + "'"); //eliminamos los datos que queramos de la bd en el resultset.
        } catch (SQLException ex) {
            Logger.getLogger(Pantallaconsulta.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "No se puede conectar a la base de datos");
        }
        JOptionPane.showMessageDialog(null, "Se ha eliminado correctamente");
    }//GEN-LAST:event_btEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminar;
    private javax.swing.JLabel lbEliminar;
    private javax.swing.JLabel tfGrupo2;
    private javax.swing.JTextField tfGrupo3;
    private javax.swing.JLabel tfTitulo2;
    private javax.swing.JTextField tfTitulo3;
    // End of variables declaration//GEN-END:variables
}
